version: '3.8'

services:
  keycloak:
    image: quay.io/keycloak/keycloak:24.0.1
    container_name: global-exchange-keycloak
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8080:8080"
    volumes:
      - keycloak_data:/opt/keycloak/data
    command: start-dev

  mailpit:
    image: axllent/mailpit:latest
    container_name: global-exchange-mailpit
    ports:
      - "1025:1025"
      - "8025:8025"

volumes:
  keycloak_data:
