# Generated by Django 6.1 on 2026-08-31 09:34

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_code', models.CharField(max_length=10, unique=True, verbose_name='Código de Divisa')),
                ('currency_name', models.CharField(max_length=100, verbose_name='Nombre de Divisa')),
                ('buy_rate', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=12, verbose_name='Tasa de Compra (Gs)')),
                ('sell_rate', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=12, verbose_name='Tasa de Venta (Gs)')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
            ],
        ),
    ]
