# Generated by Django 6.1 on 2026-09-10 23:23

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasas_cambio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRateHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_code', models.CharField(max_length=10, verbose_name='Código de Divisa')),
                ('buy_rate', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=12, verbose_name='Tasa de Compra (Gs)')),
                ('sell_rate', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=12, verbose_name='Tasa de Venta (Gs)')),
                ('timestamp', models.DateTimeField(verbose_name='Fecha y Hora del Registro')),
            ],
            options={
                'verbose_name': 'Historial de Tasa de Cambio',
                'verbose_name_plural': 'Historiales de Tasas de Cambio',
                'ordering': ['timestamp'],
            },
        ),
    ]
