# Generated by Django 6.1 on 2026-09-11 01:03

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasas_cambio', '0002_exchangeratehistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientBenefitRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_code', models.CharField(max_length=20, unique=True, verbose_name='Código de Categoría')),
                ('category_name', models.CharField(max_length=100, verbose_name='Nombre de Categoría')),
                ('min_operation_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Monto Mínimo Operación (Gs)')),
                ('benefit_percentage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='Porcentaje de Beneficio (%)')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción / Condiciones')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
            ],
            options={
                'verbose_name': 'Regla de Beneficio por Categoría',
                'verbose_name_plural': 'Reglas de Beneficios por Categorías',
            },
        ),
    ]
