# Generated by Django 6.1 on 2026-09-11 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasas_cambio', '0003_clientbenefitrule'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Código de Método de Pago')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre del Método de Pago')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('is_active', models.BooleanField(default=True, verbose_name='Habilitado / Activo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
            ],
            options={
                'verbose_name': 'Método de Pago',
                'verbose_name_plural': 'Métodos de Pago',
            },
        ),
        migrations.AddField(
            model_name='exchangerate',
            name='symbol',
            field=models.CharField(default='$', max_length=10, verbose_name='Símbolo Cambiario'),
        ),
    ]
