# Generated by Django 6.1 on 2026-09-20 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasas_cambio', '0004_paymentmethod_exchangerate_symbol'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethod',
            name='account_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Número de Cuenta / Tarjeta'),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='account_type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Tipo de Cuenta'),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Banco / Emisor'),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='holder_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Titular'),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='method_type',
            field=models.CharField(choices=[('TARJETA_CREDITO', 'Tarjeta de Crédito'), ('TARJETA_DEBITO', 'Tarjeta de Débito'), ('TRANSFERENCIA', 'Transferencia Bancaria'), ('BILLETERA', 'Billetera Electrónica'), ('EFECTIVO', 'Efectivo en Sucursal'), ('OTRO', 'Otro / Personalizado')], default='TRANSFERENCIA', max_length=30, verbose_name='Tipo de Método de Pago'),
        ),
    ]
