# Generated by Django 6.1 on 2026-09-20 20:19

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_alter_cliente_tipo_cliente'),
        ('tasas_cambio', '0005_paymentmethod_account_number_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethod',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('5000000000.00'), max_digits=18, verbose_name='Saldo Disponible (Gs)'),
        ),
        migrations.CreateModel(
            name='CurrencyPurchaseTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_currency', models.CharField(max_length=10, verbose_name='Moneda Origen')),
                ('to_currency', models.CharField(max_length=10, verbose_name='Moneda Destino')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Monto Origen')),
                ('converted_amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Monto Convertido')),
                ('applied_rate', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='Tasa Aplicada')),
                ('standard_rate', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='Tasa Estándar')),
                ('benefit_percentage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='Descuento por Perfil (%)')),
                ('commission_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Comisión (Gs)')),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Impuestos (Gs)')),
                ('total_pyg', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Total en Guaraníes (PYG)')),
                ('status', models.CharField(default='SUCCESS', max_length=20, verbose_name='Estado de Transacción')),
                ('processing_time_ms', models.IntegerField(default=0, verbose_name='Tiempo de Procesamiento (ms)')),
                ('transparent_breakdown', models.TextField(blank=True, null=True, verbose_name='Desglose Transparente')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Operación')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.cliente', verbose_name='Cliente')),
                ('payment_method', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasas_cambio.paymentmethod', verbose_name='Método de Pago')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Transacción de Compra de Divisas',
                'verbose_name_plural': 'Transacciones de Compra de Divisas',
                'ordering': ['-timestamp'],
            },
        ),
    ]
