# Generated by Django 6.1 on 2026-09-21 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasas_cambio', '0006_paymentmethod_balance_currencypurchasetransaction'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CurrencyPurchaseTransaction',
        ),
    ]
