# Generated by Django 6.1 on 2026-10-08 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasas_cambio', '0007_delete_currencypurchasetransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethod',
            name='swift_iban',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Código SWIFT / IBAN'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='method_type',
            field=models.CharField(choices=[('TARJETA_CREDITO', 'Tarjeta de Crédito (Stripe/Bancard)'), ('TARJETA_DEBITO', 'Tarjeta de Débito (Débito Directo)'), ('CUENTA_BANCARIA_LOCAL', 'Cuenta Bancaria Local (SIPAP)'), ('BILLETERA_ELECTRONICA', 'Billetera Electrónica (Tigo Money/Personal)'), ('CUENTA_BANCARIA_EXTRANJERA', 'Cuenta Bancaria Extranjera (SWIFT/IBAN)'), ('TRANSFERENCIA', 'Transferencia Bancaria'), ('BILLETERA', 'Billetera Electrónica'), ('EFECTIVO', 'Efectivo en Sucursal'), ('OTRO', 'Otro / Personalizado')], default='TRANSFERENCIA', max_length=40, verbose_name='Tipo de Método de Pago'),
        ),
    ]
