# Generated by Django 6.1 on 2026-10-08 20:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasas_cambio', '0008_paymentmethod_swift_iban_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_code', models.CharField(max_length=10, verbose_name='Código de Divisa')),
                ('condition_type', models.CharField(choices=[('COMPRA', 'Tasa de Compra'), ('VENTA', 'Tasa de Venta')], default='COMPRA', max_length=20, verbose_name='Tipo de Tasa')),
                ('target_rate', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='Tasa Objetivo (Gs)')),
                ('notification_channel', models.CharField(choices=[('EMAIL', 'Correo Electrónico (Email)'), ('PUSH', 'Notificación Push en Tiempo Real'), ('AMBOS', 'Email y Push')], default='EMAIL', max_length=20, verbose_name='Canal de Notificación')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('triggered', models.BooleanField(default=False, verbose_name='Disparada')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario Propietario')),
            ],
            options={
                'verbose_name': 'Alerta de Tasa de Cambio',
                'verbose_name_plural': 'Alertas de Tasas de Cambio',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título de Notificación')),
                ('message', models.TextField(verbose_name='Mensaje')),
                ('notification_type', models.CharField(choices=[('ALERTA_TASA', 'Alerta de Tasa Objetivo'), ('VARIACION_ABRUPTA', 'Variación Abrupta de Mercado')], default='ALERTA_TASA', max_length=50, verbose_name='Tipo de Notification')),
                ('channel', models.CharField(choices=[('EMAIL', 'Email'), ('PUSH', 'Push'), ('AMBOS', 'Email y Push')], default='PUSH', max_length=20, verbose_name='Canal')),
                ('is_read', models.BooleanField(default=False, verbose_name='Leída')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario Destinatario')),
            ],
            options={
                'verbose_name': 'Registro de Notificación',
                'verbose_name_plural': 'Registros de Notificaciones',
                'ordering': ['-created_at'],
            },
        ),
    ]
