# Generated by Django 6.1 on 2026-08-30 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='ci_ruc',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Cédula o RUC'),
        ),
    ]
