# Generated by Django 6.1 on 2026-08-31 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_userprofile_ci_ruc'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='category',
            field=models.CharField(choices=[('MINORISTA', 'Minorista'), ('CORPORATIVO', 'Corporativo'), ('VIP', 'VIP')], default='MINORISTA', max_length=20, verbose_name='Categoría de Cliente'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='transaction_volume',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Volumen Transaccional (Gs)'),
        ),
    ]
