# Generated by Django 6.1 on 2026-08-31 06:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_userprofile_category_userprofile_transaction_volume'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorporateGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=255, unique=True, verbose_name='Nombre del Grupo Corporate')),
                ('keycloak_group_id', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='ID de Grupo en Keycloak')),
                ('juridica_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corporate_group', to='authentication.userprofile', verbose_name='Perfil Persona Jurídica')),
            ],
        ),
        migrations.CreateModel(
            name='GroupMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_in_group', models.CharField(choices=[('OPERADOR', 'Operador'), ('ANALISTA', 'Analista'), ('MIEMBRO', 'Miembro')], default='OPERADOR', max_length=20, verbose_name='Rol en el Grupo')),
                ('corporate_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='authentication.corporategroup', verbose_name='Grupo Corporativo')),
                ('fisica_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_memberships', to='authentication.userprofile', verbose_name='Perfil Persona Física')),
            ],
            options={
                'unique_together': {('corporate_group', 'fisica_profile')},
            },
        ),
    ]
