# Generated by Django 6.1 on 2026-09-06 18:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_permission_role_is_active_role_permissions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupmembership',
            name='role_in_group',
            field=models.CharField(choices=[('JEFE', 'Jefe'), ('OPERADOR', 'Operador'), ('ANALISTA', 'Analista'), ('MIEMBRO', 'Miembro')], default='OPERADOR', max_length=20, verbose_name='Rol en el Grupo'),
        ),
        migrations.CreateModel(
            name='ClientRegistrationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=255, verbose_name='Nombre / Razón Social del Cliente')),
                ('ci_ruc', models.CharField(max_length=50, unique=True, verbose_name='Cédula o RUC')),
                ('client_type', models.CharField(choices=[('FISICA', 'Persona Física'), ('JURIDICA', 'Persona Jurídica')], default='FISICA', max_length=20, verbose_name='Tipo de Cliente')),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('APPROVED', 'Aprobado'), ('REJECTED', 'Rechazado')], default='PENDING', max_length=20, verbose_name='Estado')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Solicitud')),
                ('corporate_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registration_request', to='authentication.corporategroup', verbose_name='Grupo Creado')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_requests', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Solicitante')),
            ],
        ),
        migrations.CreateModel(
            name='MemberRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_email', models.EmailField(max_length=254, verbose_name='Correo del Usuario a Asociar')),
                ('role_requested', models.CharField(choices=[('OPERADOR', 'Operador'), ('ANALISTA', 'Analista')], default='OPERADOR', max_length=20, verbose_name='Rol Solicitado')),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('APPROVED', 'Aprobado'), ('REJECTED', 'Rechazado')], default='PENDING', max_length=20, verbose_name='Estado')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Solicitud')),
                ('corporate_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_requests', to='authentication.corporategroup', verbose_name='Grupo Cliente')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requested_memberships', to=settings.AUTH_USER_MODEL, verbose_name='Cliente Solicitante')),
            ],
        ),
    ]
