# Generated by Django 6.1 on 2026-09-08 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_alter_groupmembership_role_in_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='roles',
            field=models.ManyToManyField(blank=True, related_name='user_profiles', to='authentication.role', verbose_name='Roles Adicionales'),
        ),
        migrations.AlterField(
            model_name='groupmembership',
            name='role_in_group',
            field=models.CharField(choices=[('CLIENTE', 'Cliente'), ('OPERADOR', 'Operador'), ('ANALISTA', 'Analista'), ('MIEMBRO', 'Miembro')], default='OPERADOR', max_length=20, verbose_name='Rol en el Grupo'),
        ),
    ]
