# Generated by Django 6.1 on 2026-09-16 02:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_userprofile_roles_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre_o_razon_social', models.CharField(max_length=255, verbose_name='Nombre o Razón Social')),
                ('tipo_cliente', models.CharField(choices=[('FISICO', 'Persona Física'), ('JURIDICO', 'Persona Jurídica')], default='FISICO', max_length=20, verbose_name='Tipo de Cliente')),
                ('documento_identidad', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Cédula o RUC')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo Electrónico')),
                ('categoria', models.CharField(default='ESTANDAR', max_length=50, verbose_name='Categoría')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioClienteRelacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keycloak_user_id', models.CharField(db_index=True, max_length=255, verbose_name='Keycloak User ID')),
                ('rol_en_cliente', models.CharField(default='ADMIN', max_length=50, verbose_name='Rol en el Cliente')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios_relacionados', to='authentication.cliente', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Relación Usuario-Cliente',
                'verbose_name_plural': 'Relaciones Usuario-Cliente',
                'unique_together': {('keycloak_user_id', 'cliente')},
            },
        ),
    ]
