# Generated by Django 6.1 on 2026-09-16 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_cliente_usuarioclienterelacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='categoria',
            field=models.CharField(default='MINORISTA', max_length=50, verbose_name='Categoría'),
        ),
    ]
