# Generated by Django 6.1 on 2026-09-16 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_alter_cliente_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='transaction_volume',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Volumen Transaccional (Gs)'),
        ),
    ]
