# Generated by Django 6.1 on 2026-09-20 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_cliente_transaction_volume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='tipo_cliente',
            field=models.CharField(choices=[('FISICA', 'Persona Física'), ('FISICO', 'Persona Física'), ('JURIDICA', 'Persona Jurídica'), ('JURIDICO', 'Persona Jurídica')], default='FISICA', max_length=20, verbose_name='Tipo de Cliente'),
        ),
    ]
