# Generated by Django 6.1 on 2026-09-21 20:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_alter_cliente_tipo_cliente'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientAccreditationMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_medio', models.CharField(choices=[('CUENTA_BANCARIA', 'Cuenta Bancaria'), ('BILLETERA', 'Billetera Electrónica'), ('ALIAS', 'Alias de Transferencia')], default='CUENTA_BANCARIA', max_length=30, verbose_name='Tipo de Medio')),
                ('entidad_financiera', models.CharField(max_length=150, verbose_name='Entidad Financiera o Proveedora')),
                ('numero_cuenta_o_telefono', models.CharField(max_length=150, verbose_name='Número de Cuenta o Teléfono / Alias')),
                ('titularidad', models.CharField(max_length=200, verbose_name='Titularidad')),
                ('estado', models.CharField(choices=[('VERIFICADO', 'Verificado'), ('PENDIENTE', 'Pendiente')], default='VERIFICADO', max_length=20, verbose_name='Estado')),
                ('es_predeterminado', models.BooleanField(default=False, verbose_name='Predeterminado')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acreditation_methods', to='authentication.cliente', verbose_name='Cliente')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario Registrador')),
            ],
            options={
                'verbose_name': 'Medio de Acreditación',
                'verbose_name_plural': 'Medios de Acreditación',
                'ordering': ['-es_predeterminado', '-creado_en'],
            },
        ),
    ]
