# Generated by Django 6.1 on 2026-09-21 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0012_clientaccreditationmethod'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientaccreditationmethod',
            name='numero_cuenta_o_telefono',
        ),
        migrations.AddField(
            model_name='clientaccreditationmethod',
            name='alias_transferencia',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Alias de Transferencia'),
        ),
        migrations.AddField(
            model_name='clientaccreditationmethod',
            name='numero_cuenta',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Número de Cuenta'),
        ),
        migrations.AddField(
            model_name='clientaccreditationmethod',
            name='numero_telefono',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Número de Teléfono / Cuenta Billetera'),
        ),
        migrations.AddField(
            model_name='clientaccreditationmethod',
            name='tipo_cuenta',
            field=models.CharField(blank=True, choices=[('CORRIENTE', 'Cuenta Corriente'), ('AHORRO', 'Caja de Ahorro'), ('OTRO', 'Otro / General')], max_length=30, null=True, verbose_name='Tipo de Cuenta'),
        ),
        migrations.AlterField(
            model_name='clientaccreditationmethod',
            name='entidad_financiera',
            field=models.CharField(max_length=150, verbose_name='Banco / Entidad Financiera / Proveedor'),
        ),
    ]
