# Generated by Django 6.1 on 2026-10-02 15:15

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0015_alter_auditlog_id_alter_clientaccreditationmethod_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientaccreditationmethod',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, verbose_name='Fondo / Saldo de la Cuenta'),
        ),
        migrations.AddField(
            model_name='clientaccreditationmethod',
            name='moneda',
            field=models.CharField(choices=[('PYG', 'Guaraní (PYG)'), ('USD', 'Dólar (USD)'), ('EUR', 'Euro (EUR)'), ('BRL', 'Real (BRL)'), ('ARS', 'Peso Argentino (ARS)')], default='PYG', max_length=10, verbose_name='Moneda de la Cuenta'),
        ),
    ]
