# Generated by Django 6.1 on 2026-10-06 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0016_clientaccreditationmethod_balance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientaccreditationmethod',
            name='fecha_expiracion',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Fecha de Expiración (MM/AA)'),
        ),
        migrations.AddField(
            model_name='clientaccreditationmethod',
            name='numero_tarjeta',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Número de Tarjeta'),
        ),
        migrations.AlterField(
            model_name='clientaccreditationmethod',
            name='tipo_medio',
            field=models.CharField(choices=[('CUENTA_BANCARIA', 'Cuenta Bancaria'), ('BILLETERA', 'Billetera Electrónica'), ('ALIAS', 'Alias de Transferencia'), ('TARJETA_CREDITO', 'Tarjeta de Crédito'), ('TARJETA_DEBITO', 'Tarjeta de Débito')], default='CUENTA_BANCARIA', max_length=30, verbose_name='Tipo de Medio'),
        ),
    ]
