# Generated by Django 6.1 on 2026-10-08 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0017_clientaccreditationmethod_fecha_expiracion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientaccreditationmethod',
            name='swift_iban',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Código SWIFT / IBAN'),
        ),
        migrations.AlterField(
            model_name='clientaccreditationmethod',
            name='tipo_medio',
            field=models.CharField(choices=[('TARJETA_CREDITO', 'Tarjeta de Crédito (Crédito Local/Internacional - Stripe/Bancard)'), ('TARJETA_DEBITO', 'Tarjeta de Débito (Débito Directo)'), ('CUENTA_BANCARIA_LOCAL', 'Cuenta Bancaria Local (Caja de Ahorro / Cta. Cte. - SIPAP)'), ('BILLETERA_ELECTRONICA', 'Billetera Electrónica (Móvil - Tigo Money/Personal)'), ('CUENTA_BANCARIA_EXTRANJERA', 'Cuenta Bancaria Extranjera (Transferencia Internacional SWIFT/IBAN)'), ('CUENTA_BANCARIA', 'Cuenta Bancaria'), ('BILLETERA', 'Billetera Electrónica'), ('ALIAS', 'Alias de Transferencia')], default='CUENTA_BANCARIA_LOCAL', max_length=40, verbose_name='Tipo de Medio'),
        ),
    ]
