# Generated by Django 6.1 on 2026-10-07 18:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0017_clientaccreditationmethod_fecha_expiracion_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentGatewayLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gateway_name', models.CharField(choices=[('BANCARD', 'Bancard API'), ('TIGO_MONEY', 'Tigo Money API'), ('SIPAP', 'SIPAP Red Interbancaria')], max_length=30, verbose_name='Pasarela / Red')),
                ('transaction_type', models.CharField(default='TRANSFER', max_length=30, verbose_name='Tipo de Operación')),
                ('reference_code', models.CharField(max_length=100, unique=True, verbose_name='Código de Referencia')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Monto')),
                ('currency', models.CharField(default='PYG', max_length=10, verbose_name='Moneda')),
                ('status', models.CharField(choices=[('SUCCESS', 'Exitoso'), ('FAILED', 'Fallido'), ('TIMEOUT', 'Tiempo Agotado'), ('PENDING', 'Pendiente')], default='SUCCESS', max_length=20, verbose_name='Estado')),
                ('request_payload', models.TextField(blank=True, null=True, verbose_name='Payload de Solicitud')),
                ('response_payload', models.TextField(blank=True, null=True, verbose_name='Payload de Respuesta')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='Mensaje de Error')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora')),
            ],
            options={
                'verbose_name': 'Log de Pasarela de Pago',
                'verbose_name_plural': 'Logs de Pasarelas de Pago',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='WithdrawalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('SIPAP', 'SIPAP Transferencia Interbancaria 24/7'), ('BANCARD', 'Bancard Pago/Cobro Digital'), ('TIGO_MONEY', 'Billetera Tigo Money'), ('WESTERN_UNION', 'Western Union Internacional'), ('EURO_TRANSFER', 'EuroTransfer Internacional'), ('PICKUP_CAJA', 'Retiro Físico en Caja (Pickup)')], max_length=30, verbose_name='Canal de Acreditación/Retiro')),
                ('currency', models.CharField(default='PYG', max_length=10, verbose_name='Moneda')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Monto')),
                ('destination_detail', models.CharField(max_length=255, verbose_name='Detalle de Cuenta / Destino / Teléfono')),
                ('status', models.CharField(choices=[('PROCESSING', 'Procesando 24/7'), ('COMPLETED', 'Completado y Acreditado'), ('FAILED', 'Fallido / Rechazado'), ('PENDING_APPROVAL', 'Pendiente de Aprobación')], default='PROCESSING', max_length=20, verbose_name='Estado de Acreditación')),
                ('gateway_ref', models.CharField(blank=True, max_length=100, null=True, verbose_name='Referencia Externa Gateway')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Solicitud')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.cliente', verbose_name='Cliente')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Solicitud de Retiro / Acreditación',
                'verbose_name_plural': 'Solicitudes de Retiros y Acreditaciones',
                'ordering': ['-timestamp'],
            },
        ),
    ]
