# Generated by Django 6.1 on 2026-10-08 19:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Caja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre de Caja')),
                ('codigo', models.CharField(max_length=50, unique=True, verbose_name='Código')),
                ('activa', models.BooleanField(default=True, verbose_name='Activa')),
            ],
            options={
                'verbose_name': 'Caja',
                'verbose_name_plural': 'Cajas',
            },
        ),
        migrations.CreateModel(
            name='TurnoCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_apertura', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora de Apertura')),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y Hora de Cierre')),
                ('estado', models.CharField(choices=[('ABIERTO', 'Abierto'), ('CERRADO', 'Cerrado')], default='ABIERTO', max_length=20, verbose_name='Estado de Turno')),
                ('saldo_inicial_pyg', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Saldo Inicial PYG')),
                ('saldo_inicial_usd', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Saldo Inicial USD')),
                ('saldo_inicial_eur', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Saldo Inicial EUR')),
                ('saldo_inicial_brl', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Saldo Inicial BRL')),
                ('saldo_inicial_ars', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Saldo Inicial ARS')),
                ('saldo_final_pyg', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Saldo Final PYG')),
                ('saldo_final_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Saldo Final USD')),
                ('saldo_final_eur', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Saldo Final EUR')),
                ('saldo_final_brl', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Saldo Final BRL')),
                ('saldo_final_ars', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Saldo Final ARS')),
                ('caja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caja.caja', verbose_name='Caja')),
                ('cajero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Cajero')),
            ],
            options={
                'verbose_name': 'Turno de Caja',
                'verbose_name_plural': 'Turnos de Caja',
            },
        ),
    ]
