# Generated by Django 6.1 on 2026-10-08 20:01

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DenominacionDivisa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('divisa', models.CharField(max_length=10, verbose_name='Código de Divisa')),
                ('valor_facial', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor Facial')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre de Denominación')),
                ('activa', models.BooleanField(default=True, verbose_name='Activa')),
            ],
            options={
                'verbose_name': 'Denominación de Divisa',
                'verbose_name_plural': 'Denominaciones de Divisas',
                'ordering': ['divisa', '-valor_facial'],
            },
        ),
        migrations.CreateModel(
            name='DesgloseEfectivoCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_operacion', models.CharField(choices=[('APERTURA', 'Apertura de Turno'), ('CIERRE', 'Cierre de Turno'), ('INGRESO', 'Ingreso Físico de Efectivo'), ('SALIDA', 'Salida Física de Efectivo')], max_length=20, verbose_name='Tipo de Operación')),
                ('divisa', models.CharField(max_length=10, verbose_name='Divisa')),
                ('monto_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Monto Total')),
                ('observacion', models.TextField(blank=True, null=True, verbose_name='Observación')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora')),
                ('turno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='desgloses_efectivo', to='caja.turnocaja', verbose_name='Turno de Caja')),
            ],
            options={
                'verbose_name': 'Desglose de Efectivo de Caja',
                'verbose_name_plural': 'Desgloses de Efectivo de Caja',
            },
        ),
        migrations.CreateModel(
            name='DetalleDesgloseBillete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=0, verbose_name='Cantidad de Billetes')),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Subtotal')),
                ('denominacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caja.denominaciondivisa', verbose_name='Denominación')),
                ('desglose', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='caja.desgloseefectivocaja', verbose_name='Desglose')),
            ],
            options={
                'verbose_name': 'Detalle de Billete',
                'verbose_name_plural': 'Detalles de Billetes',
            },
        ),
    ]
