# Generated by Django 6.1 on 2026-10-08 20:20

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0002_denominaciondivisa_desgloseefectivocaja_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArqueoCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('divisa', models.CharField(max_length=10, verbose_name='Divisa')),
                ('saldo_inicial', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Saldo Inicial')),
                ('movimientos_sistema', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Movimientos del Sistema')),
                ('saldo_teorico', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Saldo Teórico Esperado')),
                ('saldo_fisico_cierre', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Saldo Físico de Cierre')),
                ('diferencia', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Diferencia')),
                ('estado_arqueo', models.CharField(choices=[('CUADRADO', 'Cuadrado'), ('FALTANTE', 'Faltante'), ('SOBRANTE', 'Sobrante')], default='CUADRADO', max_length=20, verbose_name='Estado de Arqueo')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Arqueo')),
                ('turno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arqueos', to='caja.turnocaja', verbose_name='Turno de Caja')),
            ],
            options={
                'verbose_name': 'Arqueo de Caja',
                'verbose_name_plural': 'Arqueos de Caja',
                'ordering': ['-fecha', 'divisa'],
            },
        ),
        migrations.CreateModel(
            name='BitacoraArqueo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('divisa', models.CharField(max_length=10, verbose_name='Divisa')),
                ('tipo_descuadre', models.CharField(choices=[('FALTANTE', 'Faltante'), ('SOBRANTE', 'Sobrante')], max_length=20, verbose_name='Tipo de Descuadre')),
                ('monto_diferencia', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Monto de Diferencia')),
                ('mensaje', models.TextField(verbose_name='Mensaje de Alerta / Bitácora')),
                ('administrador_notificado', models.BooleanField(default=True, verbose_name='Administrador Notificado')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora de Registro')),
                ('turno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bitacoras_arqueo', to='caja.turnocaja', verbose_name='Turno de Caja')),
            ],
            options={
                'verbose_name': 'Bitácora de Arqueo',
                'verbose_name_plural': 'Bitácoras de Arqueos',
                'ordering': ['-fecha'],
            },
        ),
    ]
