# Generated by Django 6.1 on 2026-09-21 20:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0012_clientaccreditationmethod'),
        ('procesamiento_operaciones', '0002_currencysaletransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='currencysaletransaction',
            name='acreditation_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.clientaccreditationmethod', verbose_name='Medio de Acreditación del Cliente'),
        ),
    ]
