# Generated by Django 6.1 on 2026-10-01 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procesamiento_operaciones', '0003_currencysaletransaction_acreditation_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='currencypurchasetransaction',
            name='moneda_destino_id',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Moneda Destino ID'),
        ),
        migrations.AddField(
            model_name='currencypurchasetransaction',
            name='moneda_origen_id',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Moneda Origen ID'),
        ),
        migrations.AddField(
            model_name='currencypurchasetransaction',
            name='monto_destino',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Monto Destino'),
        ),
        migrations.AddField(
            model_name='currencypurchasetransaction',
            name='monto_moneda_local',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='Monto Moneda Local (Audit)'),
        ),
        migrations.AddField(
            model_name='currencypurchasetransaction',
            name='monto_origen',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Monto Origen'),
        ),
        migrations.AddField(
            model_name='currencypurchasetransaction',
            name='tipo_cambio_cruzado',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='Tipo de Cambio Cruzado'),
        ),
        migrations.AddField(
            model_name='currencypurchasetransaction',
            name='tipo_cambio_local_origen',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='Tipo de Cambio Local Origen'),
        ),
    ]
