# Generated by Django 6.1 on 2026-10-01 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procesamiento_operaciones', '0004_currencypurchasetransaction_moneda_destino_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='currencypurchasetransaction',
            name='total_origen',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='Total en Moneda Origen'),
        ),
    ]
