# Generated by Django 6.1 on 2026-10-02 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0015_alter_auditlog_id_alter_clientaccreditationmethod_id_and_more'),
        ('procesamiento_operaciones', '0006_currencysaletransaction_moneda_destino_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='currencypurchasetransaction',
            name='destination_acreditation_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_destinations', to='authentication.clientaccreditationmethod', verbose_name='Medio de Acreditación Destino'),
        ),
        migrations.AddField(
            model_name='currencypurchasetransaction',
            name='origin_acreditation_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_origins', to='authentication.clientaccreditationmethod', verbose_name='Medio de Acreditación Origen'),
        ),
        migrations.AddField(
            model_name='currencysaletransaction',
            name='destination_acreditation_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale_destinations', to='authentication.clientaccreditationmethod', verbose_name='Medio de Acreditación Destino'),
        ),
        migrations.AddField(
            model_name='currencysaletransaction',
            name='origin_acreditation_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale_origins', to='authentication.clientaccreditationmethod', verbose_name='Medio de Acreditación Origen'),
        ),
    ]
