# Generated by Django 6.1 on 2026-10-08 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procesamiento_operaciones', '0007_currencypurchasetransaction_destination_acreditation_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='currencypurchasetransaction',
            name='gateway_reference',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Referencia de Pasarela'),
        ),
        migrations.AddField(
            model_name='currencypurchasetransaction',
            name='gateway_status',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Estado de Pasarela'),
        ),
        migrations.AddField(
            model_name='currencypurchasetransaction',
            name='payment_method_type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Tipo de Instrumento / Método de Pago'),
        ),
        migrations.AddField(
            model_name='currencysaletransaction',
            name='gateway_reference',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Referencia de Pasarela'),
        ),
        migrations.AddField(
            model_name='currencysaletransaction',
            name='gateway_status',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Estado de Pasarela'),
        ),
        migrations.AddField(
            model_name='currencysaletransaction',
            name='payment_method_type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Tipo de Instrumento / Método de Pago'),
        ),
    ]
